### ISSUE TITLE
getGEO sometimes timeout in MMGE building, but not on my laptop

### ISSUE THREAD

**Issue by huangzhii** [huangzhii/TSUNAMI#4]
e.g.:

> gse <- getGEO('GSE10')
Error in open.connection(x, "rb") : 
  Timeout was reached: Connection timed out after 10001 milliseconds

**Comment by Deliadd** [comment]
Hi, I have met the same problem but in my laptop when I try to use getGEO. Have you solved it now?

**Comment by huangzhii** [comment]
@Deliadd Can you try:
`library(GEOquery)`
`gse <- getGEO('GSE10')`

?

If that won't work, I think it might be the issue from GEOquery package. I tried and it worked from my side.
